---
- name: push docker images
  hosts: localhost
  remote_user: ubuntu
  tasks:

    - name: Build an image and push it to a repo
      community.docker.docker_image:
        build:
          path: ./backend
        name: yndxgwyn/web-backend:1.00
        tag: v1
        push: true
        source: build

