---
- name: push docker images
  hosts: test
  remote_user: ubuntu
  tasks:

    - name: Setup backend container
      community.docker.docker_container:
        name: backend
        image: yndx-gwyn/bank-web-app:latest
        state: present
        recreate: true
        exposed_ports:
          - 8080


