---
- name: push docker images
  hosts: test
  remote_user: ubuntu
  tasks:

    - name: login in docker
      ansible.builtin.command:
        cmd: docker login --username {{ username }}  --password {{ password }}

    - name: Setup backend container
      community.docker.docker_container:
        name: backend
        image: yndx-gwyn/bank-web-app
        state: present
        recreate: true
        exposed_ports:
          - 8080


