---
- name: push docker images
  hosts: test
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:

    - name: install docker
      yum: name=docker


    **- name: Ensure service is enabled
      command: service docker restart***

    - name: Log into DockerHub
      docker_login:
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Setup backend container
      community.docker.docker_container:
        name: backend
        image: yndx-gwyn/bank-web-app:latest
        state: present
        recreate: true
        exposed_ports:
          - 8080
