---
- name: push docker images
  hosts: test
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: install docker-py
      pip: name=docker-py

    - name: Ensure docker service is running
      command: service docker restart

    - name: Log into DockerHub
      docker_login:
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Setup backend
      community.docker.docker_container:
        name: backend
        image: yndxgwyn/bank-web-app
        pull: true
        state: started
        detach: true
        ports:
          - 8080:8080
        recreate: true
        restart: true
        exposed_ports:
          - 8080
